{
	_x call ace_arsenal_fnc_addDefaultLoadout;
} forEach [

[
	"APM Base Kit", 
	[[],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["APM_CombatUniformTan_Rolled",[["ACE_tourniquet",4],["ACE_RangeCard",1],["ACE_MapTools",1],["ACE_EarPlugs",2],["ACE_packingBandage",12],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_splint",2],["ACE_IR_Strobe_Item",1],["ACE_adenosine",1],["ACE_CableTie",1],["SmokeShellBlue",1,1],["SmokeShellGreen",1,1]]],["VSM_FAPC_Operator_OGA_OD",[["ACE_EntrenchingTool",1],["ACE_M26_Clacker",1],["ACE_CableTie",2],["ACE_microDAGR",1],["ACE_M84",2,1],["MiniGrenade",2,1],["SmokeShell",2,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],[],"VSM_Black_OPS","VSM_Shemagh_Balaclava2_OD_Peltor_Goggles",["Laserdesignator_03","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]]
],
[
	"APM Rifleman",
	[["rhs_weap_m4a1_blockII_KAC","hlc_muzzle_556NATO_KAC","ACE_acc_pointer_green","SMA_ELCAN_SPECTER_4z",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip2"],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["APM_CombatUniformTan_Rolled",[["ACE_tourniquet",4],["ACE_RangeCard",1],["ACE_MapTools",1],["ACE_EarPlugs",2],["ACE_packingBandage",12],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_splint",2],["ACE_IR_Strobe_Item",1],["ACE_adenosine",1],["ACE_CableTie",1],["SmokeShellBlue",1,1],["SmokeShellGreen",1,1]]],["VSM_FAPC_Operator_OGA_OD",[["ACE_EntrenchingTool",1],["ACE_M26_Clacker",1],["ACE_CableTie",2],["ACE_microDAGR",1],["ACE_M84",2,1],["MiniGrenade",2,1],["SmokeShell",2,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17],["rhs_mag_30Rnd_556x45_M855A1_PMAG",8,30]]],[],"VSM_Black_OPS","VSM_Shemagh_Balaclava2_OD_Peltor_Goggles",["Laserdesignator_03","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]]
],
[
	"APM Marksman",
	[["rhs_weap_sr25","rhsusf_acc_SR25S","ACE_acc_pointer_green","rhsusf_acc_premier_low",["rhsusf_20Rnd_762x51_SR25_mk316_special_Mag",20],[],"rhsusf_acc_harris_bipod"],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["APM_CombatUniformTan_Rolled",[["ACE_tourniquet",4],["ACE_RangeCard",1],["ACE_MapTools",1],["ACE_EarPlugs",2],["ACE_packingBandage",12],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_splint",2],["ACE_IR_Strobe_Item",1],["ACE_adenosine",1],["ACE_CableTie",1],["SmokeShellBlue",1,1],["SmokeShellGreen",1,1]]],["VSM_CarrierRig_Operator_OGA_OD",[["ACE_EntrenchingTool",1],["ACE_M26_Clacker",1],["ACE_CableTie",2],["ACE_microDAGR",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_M84",2,1],["MiniGrenade",2,1],["SmokeShell",2,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17],["rhsusf_20Rnd_762x51_SR25_mk316_special_Mag",6,20]]],[],"VSM_Bowman_cap_Black","rhs_googles_clear",["Laserdesignator_03","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ACE_Altimeter","TRYK_Shemagh_TAN_NV"]]
],
[
	"APM Grenadier",
	[["rhs_weap_mk18_m320","hlc_muzzle_556NATO_KAC","ACE_acc_pointer_green","SMA_ELCAN_SPECTER_4z",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],["1Rnd_HE_Grenade_shell",1],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["APM_CombatUniformTan_Rolled",[["ACE_tourniquet",4],["ACE_RangeCard",1],["ACE_MapTools",1],["ACE_EarPlugs",2],["ACE_packingBandage",12],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_splint",2],["ACE_IR_Strobe_Item",1],["ACE_adenosine",1],["ACE_CableTie",1],["SmokeShellBlue",1,1],["SmokeShellGreen",1,1]]],["VSM_LBT6094_operator_OGA_OD",[["ACE_EntrenchingTool",1],["ACE_M26_Clacker",1],["ACE_CableTie",2],["ACE_microDAGR",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_M84",2,1],["MiniGrenade",2,1],["SmokeShell",2,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30]]],["VSM_OGA_OD_Backpack_Compact",[["1Rnd_HE_Grenade_shell",6,1],["1Rnd_Smoke_Grenade_shell",4,1],["1Rnd_SmokeRed_Grenade_shell",2,1],["1Rnd_SmokeBlue_Grenade_shell",2,1],["ACE_40mm_Flare_white",4,1],["ACE_40mm_Flare_ir",4,1]]],"VSM_OD_spray_OPS","rhs_googles_clear",["Laserdesignator_03","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ACE_Altimeter","TRYK_Shemagh_TAN_NV"]]
],
[
	"APM Autorifleman",
	[["LMG_03_F","muzzle_snds_H_MG_blk_F","ACE_acc_pointer_green","SMA_ELCAN_SPECTER_ARDRDS_4z",["200Rnd_556x45_Box_Red_F",200],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["APM_CombatUniformTan_Rolled",[["ACE_tourniquet",4],["ACE_RangeCard",1],["ACE_MapTools",1],["ACE_EarPlugs",2],["ACE_packingBandage",12],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_splint",2],["ACE_IR_Strobe_Item",1],["ACE_adenosine",1],["ACE_CableTie",1],["SmokeShellBlue",1,1],["SmokeShellGreen",1,1]]],["VSM_LBT6094_MG_OGA_OD",[["ACE_EntrenchingTool",1],["ACE_M26_Clacker",1],["ACE_CableTie",2],["ACE_microDAGR",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_M84",2,1],["MiniGrenade",2,1],["SmokeShell",2,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17],["200Rnd_556x45_Box_Tracer_Red_F",4,200]]],[],"VSM_Mich2000_2_CamoSprayOD","VSM_Shemagh_Balaclava2_OD_Goggles",["Laserdesignator_03","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]]
],
[
	"APM Heavy AT",
	[["rhs_weap_mk18_KAC","hlc_muzzle_556NATO_KAC","ACE_acc_pointer_green","SMA_BARSKA",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_kac_grip"],["launch_MRAWS_green_F","","","",["MRAWS_HEAT_F",1],[],""],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["APM_CombatUniformTan_Rolled",[["ACE_tourniquet",4],["ACE_RangeCard",1],["ACE_MapTools",1],["ACE_EarPlugs",2],["ACE_packingBandage",12],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_splint",2],["ACE_IR_Strobe_Item",1],["ACE_adenosine",1],["ACE_CableTie",1],["SmokeShellBlue",1,1],["SmokeShellGreen",1,1]]],["VSM_FAPC_Operator_OGA_OD",[["ACE_EntrenchingTool",1],["ACE_M26_Clacker",1],["ACE_CableTie",2],["ACE_microDAGR",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_M84",2,1],["MiniGrenade",2,1],["SmokeShell",2,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30]]],["VSM_OGA_OD_Backpack_Kitbag",[["MRAWS_HEAT_F",4,1]]],"VSM_Bowman_cap_Tan","VSM_Facemask_black_Peltor_Goggles",["Laserdesignator_03","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ACE_Altimeter","TRYK_Shemagh_TAN_NV"]]
],
[
	"APM Breacher",
	[["rhs_weap_mk18_KAC","hlc_muzzle_556NATO_KAC","ACE_acc_pointer_green","SMA_BARSKA",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_kac_grip"],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["APM_CombatUniformTan_Rolled",[["ACE_tourniquet",4],["ACE_RangeCard",1],["ACE_MapTools",1],["ACE_EarPlugs",2],["ACE_packingBandage",12],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_splint",2],["ACE_IR_Strobe_Item",1],["ACE_adenosine",1],["ACE_CableTie",1],["SmokeShellBlue",1,1],["SmokeShellGreen",1,1]]],["VSM_FAPC_Operator_OGA_OD",[["ACE_EntrenchingTool",1],["ACE_M26_Clacker",1],["ACE_CableTie",2],["ACE_microDAGR",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_M84",4,1],["MiniGrenade",4,1],["SmokeShell",2,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17],["rhs_mag_30Rnd_556x45_M855A1_PMAG",12,30]]],[],"VSM_Beanie_Black","rhs_googles_clear",["Laserdesignator_03","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ACE_Altimeter","TRYK_Shemagh_TAN_NV"]]
]

];