class VSM_SMG_Blk: None
{
  author="LinkIsParking";
  scope=2;
  displayname="[VSM] Scarf (Black Plain)";
  model="\WAINO\data\W_smg.p3d";
  picture = "\VSM_OGA\Data\Icons\VSM_OGA_grey.paa";
  hiddenSelections[]=
  {
    "camo"
  };
  hiddenSelectionsTextures[]=
  {
    "\VSM_Shemagh\Textures\VSM_Shemagh_Black_Plain"
  };
  identityTypes[]=
  {
    "NoGlasses",
    0,
    "G_NATO_default",
    0,
    "G_NATO_casual",
    0,
    "G_NATO_pilot",
    0,
    "G_NATO_recon",
    0,
    "G_NATO_SF",
    0,
    "G_NATO_sniper",
    0,
    "G_NATO_diver",
    0,
    "G_IRAN_default",
    0,
    "G_IRAN_diver",
    0,
    "G_GUERIL_default",
    0,
    "G_HAF_default",
    0,
    "G_CIVIL_female",
    0,
    "G_CIVIL_male",
    0
  };
};
class VSM_SMG_Bl: None
{
  author="LinkIsParking";
  scope=2;
  displayname="[VSM] Scarf (Black)";
  model="\WAINO\data\W_smg.p3d";
  picture = "\VSM_OGA\Data\Icons\VSM_OGA_Grey.paa";
  hiddenSelections[]=
  {
    "camo"
  };
  hiddenSelectionsTextures[]=
  {
    "\VSM_Shemagh\Textures\VSM_Shemagh_Black"
  };
  identityTypes[]=
  {
    "NoGlasses",
    0,
    "G_NATO_default",
    0,
    "G_NATO_casual",
    0,
    "G_NATO_pilot",
    0,
    "G_NATO_recon",
    0,
    "G_NATO_SF",
    0,
    "G_NATO_sniper",
    0,
    "G_NATO_diver",
    0,
    "G_IRAN_default",
    0,
    "G_IRAN_diver",
    0,
    "G_GUERIL_default",
    0,
    "G_HAF_default",
    0,
    "G_CIVIL_female",
    0,
    "G_CIVIL_male",
    0
  };
};
class VSM_SMG_OD: None
{
  author="LinkIsParking";
  scope=2;
  displayname="[VSM] Scarf (Olive)";
  model="\WAINO\data\W_smg.p3d";
  picture = "\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
  hiddenSelections[]=
  {
    "camo"
  };
  hiddenSelectionsTextures[]=
  {
    "\VSM_Shemagh\Textures\VSM_Shemagh_Olive"
  };
  identityTypes[]=
  {
    "NoGlasses",
    0,
    "G_NATO_default",
    0,
    "G_NATO_casual",
    0,
    "G_NATO_pilot",
    0,
    "G_NATO_recon",
    0,
    "G_NATO_SF",
    0,
    "G_NATO_sniper",
    0,
    "G_NATO_diver",
    0,
    "G_IRAN_default",
    0,
    "G_IRAN_diver",
    0,
    "G_GUERIL_default",
    0,
    "G_HAF_default",
    0,
    "G_CIVIL_female",
    0,
    "G_CIVIL_male",
    0
  };
};
class VSM_SMG_OD_Plain: None
{
  author="LinkIsParking";
  scope=2;
  displayname="[VSM] Scarf (Olive Plain)";
  model="\WAINO\data\W_smg.p3d";
  picture = "\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
  hiddenSelections[]=
  {
    "camo"
  };
  hiddenSelectionsTextures[]=
  {
    "\VSM_Shemagh\Textures\VSM_Shemagh_Olive_Plain"
  };
  identityTypes[]=
  {
    "NoGlasses",
    0,
    "G_NATO_default",
    0,
    "G_NATO_casual",
    0,
    "G_NATO_pilot",
    0,
    "G_NATO_recon",
    0,
    "G_NATO_SF",
    0,
    "G_NATO_sniper",
    0,
    "G_NATO_diver",
    0,
    "G_IRAN_default",
    0,
    "G_IRAN_diver",
    0,
    "G_GUERIL_default",
    0,
    "G_HAF_default",
    0,
    "G_CIVIL_female",
    0,
    "G_CIVIL_male",
    0
  };
};
class VSM_SMG_Tan: None
{
  author="LinkIsParking";
  scope=2;
  displayname="[VSM] Scarf (Tan)";
  model="\WAINO\data\W_smg.p3d";
  picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
  hiddenSelections[]=
  {
    "camo"
  };
  hiddenSelectionsTextures[]=
  {
    "\VSM_Shemagh\Textures\VSM_Shemagh_Tan"
  };
  identityTypes[]=
  {
    "NoGlasses",
    0,
    "G_NATO_default",
    0,
    "G_NATO_casual",
    0,
    "G_NATO_pilot",
    0,
    "G_NATO_recon",
    0,
    "G_NATO_SF",
    0,
    "G_NATO_sniper",
    0,
    "G_NATO_diver",
    0,
    "G_IRAN_default",
    0,
    "G_IRAN_diver",
    0,
    "G_GUERIL_default",
    0,
    "G_HAF_default",
    0,
    "G_CIVIL_female",
    0,
    "G_CIVIL_male",
    0
  };
};
class VSM_SMG_Tan_Plain: None
{
  author="LinkIsParking";
  scope=2;
  displayname="[VSM] Scarf (Tan Plain)";
  model="\WAINO\data\W_smg.p3d";
  picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
  hiddenSelections[]=
  {
    "camo"
  };
  hiddenSelectionsTextures[]=
  {
    "\VSM_Shemagh\Textures\VSM_Shemagh_Tan_Plain"
  };
  identityTypes[]=
  {
    "NoGlasses",
    0,
    "G_NATO_default",
    0,
    "G_NATO_casual",
    0,
    "G_NATO_pilot",
    0,
    "G_NATO_recon",
    0,
    "G_NATO_SF",
    0,
    "G_NATO_sniper",
    0,
    "G_NATO_diver",
    0,
    "G_IRAN_default",
    0,
    "G_IRAN_diver",
    0,
    "G_GUERIL_default",
    0,
    "G_HAF_default",
    0,
    "G_CIVIL_female",
    0,
    "G_CIVIL_male",
    0
  };
};
